services:
    GpsLab\Bundle\GeoIP2Bundle\Database\ProxyReader:
        arguments: [ '%geoip2.cache%', '%geoip2.locales%' ]
        public: false

    GpsLab\Bundle\GeoIP2Bundle\Database\Reader:
        alias: 'GpsLab\Bundle\GeoIP2Bundle\Database\ProxyReader'
        public: true

    GpsLab\Bundle\GeoIP2Bundle\Command\UpdateDatabaseCommand:
        arguments:
            - '@filesystem'
            - '@debug.stopwatch'
            - '@GpsLab\Component\Compressor\GzipCompressor'
            - '%geoip2.url%'
            - '%geoip2.cache%'
        tags:
            - { name: console.command }

    GpsLab\Component\Compressor\GzipCompressor:
        public: false
