services:
    gpslab.geoip2.compressor:
        class: 'GpsLab\Component\Compressor\GzipCompressor'
        public: false

    gpslab.geoip2.update_database_command:
        class: 'GpsLab\Bundle\GeoIP2Bundle\Command\UpdateDatabaseCommand'
        arguments:
            - '@filesystem'
            - '@gpslab.geoip2.compressor'
            - '%geoip2.url%'
            - '%geoip2.cache%'
        calls:
            - [setStopwatch, ['@?debug.stopwatch']]
        tags:
            - { name: console.command }

    gpslab.geoip2.proxy_reader:
        class: 'GpsLab\Bundle\GeoIP2Bundle\Database\ProxyReader'
        arguments: [ '%geoip2.cache%', '%geoip2.locales%' ]
        public: false

    GpsLab\Bundle\GeoIP2Bundle\Database\Reader:
        alias: 'gpslab.geoip2.proxy_reader'
        public: true

    geoip2.reader:
        alias: 'gpslab.geoip2.proxy_reader'
        public: true
